-- MySQL Script generated by MySQL Workbench
-- Fri 03 Nov 2017 01:58:34 AM -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crossover-auction-dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crossover-auction-dev` ;

-- -----------------------------------------------------
-- Schema crossover-auction-dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crossover-auction-dev` DEFAULT CHARACTER SET utf8 ;
USE `crossover-auction-dev` ;

-- -----------------------------------------------------
-- Table `crossover-auction-dev`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-dev`.`user` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-dev`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `coins` DECIMAL(7,2) NOT NULL DEFAULT 1000,00,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-dev`.`user` (`id` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `crossover-auction-dev`.`user` (`username` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-dev`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-dev`.`item` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-dev`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `imagePath` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-dev`.`item` (`id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-dev`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-dev`.`inventory` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-dev`.`inventory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `amount` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `item_id`),
  CONSTRAINT `fk_inventory_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover-auction-dev`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `crossover-auction-dev`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-dev`.`inventory` (`id` ASC);

CREATE INDEX `fk_inventory_user1_idx` ON `crossover-auction-dev`.`inventory` (`user_id` ASC);

CREATE INDEX `fk_inventory_item1_idx` ON `crossover-auction-dev`.`inventory` (`item_id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-dev`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-dev`.`errors` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-dev`.`errors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  `request` TEXT NOT NULL,
  `error` TEXT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_errors_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover-auction-dev`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-dev`.`errors` (`id` ASC);

CREATE INDEX `fk_errors_user1_idx` ON `crossover-auction-dev`.`errors` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-dev`.`traceLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-dev`.`traceLog` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-dev`.`traceLog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_traceLog_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover-auction-dev`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-dev`.`traceLog` (`id` ASC);

CREATE INDEX `fk_traceLog_user1_idx` ON `crossover-auction-dev`.`traceLog` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-dev`.`auctionLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-dev`.`auctionLog` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-dev`.`auctionLog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seller` INT UNSIGNED NOT NULL,
  `buyer` INT UNSIGNED NOT NULL,
  `bid` DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT 0,
  `item_id` INT UNSIGNED NOT NULL,
  `amount` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `item_id`),
  CONSTRAINT `fk_auctionLog_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `crossover-auction-dev`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-dev`.`auctionLog` (`id` ASC);

CREATE INDEX `fk_auctionLog_item1_idx` ON `crossover-auction-dev`.`auctionLog` (`item_id` ASC);


-- -----------------------------------------------------
-- Schema crossover-auction-prod
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crossover-auction-prod` ;

-- -----------------------------------------------------
-- Schema crossover-auction-prod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crossover-auction-prod` DEFAULT CHARACTER SET utf8 ;
USE `crossover-auction-prod` ;

-- -----------------------------------------------------
-- Table `crossover-auction-prod`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-prod`.`user` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-prod`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `coins` DECIMAL(7,2) NOT NULL DEFAULT 1000,00,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-prod`.`user` (`id` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `crossover-auction-prod`.`user` (`username` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-prod`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-prod`.`item` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-prod`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `imagePath` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-prod`.`item` (`id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-prod`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-prod`.`inventory` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-prod`.`inventory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `amount` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `item_id`),
  CONSTRAINT `fk_inventory_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover-auction-prod`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `crossover-auction-prod`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-prod`.`inventory` (`id` ASC);

CREATE INDEX `fk_inventory_user1_idx` ON `crossover-auction-prod`.`inventory` (`user_id` ASC);

CREATE INDEX `fk_inventory_item1_idx` ON `crossover-auction-prod`.`inventory` (`item_id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-prod`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-prod`.`errors` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-prod`.`errors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  `request` TEXT NOT NULL,
  `error` TEXT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_errors_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover-auction-prod`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-prod`.`errors` (`id` ASC);

CREATE INDEX `fk_errors_user1_idx` ON `crossover-auction-prod`.`errors` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-prod`.`traceLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-prod`.`traceLog` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-prod`.`traceLog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_traceLog_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `crossover-auction-prod`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-prod`.`traceLog` (`id` ASC);

CREATE INDEX `fk_traceLog_user1_idx` ON `crossover-auction-prod`.`traceLog` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `crossover-auction-prod`.`auctionLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crossover-auction-prod`.`auctionLog` ;

CREATE TABLE IF NOT EXISTS `crossover-auction-prod`.`auctionLog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seller` INT UNSIGNED NOT NULL,
  `buyer` INT UNSIGNED NOT NULL,
  `bid` DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT 0,
  `item_id` INT UNSIGNED NOT NULL,
  `amount` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `item_id`),
  CONSTRAINT `fk_auctionLog_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `crossover-auction-prod`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `crossover-auction-prod`.`auctionLog` (`id` ASC);

CREATE INDEX `fk_auctionLog_item1_idx` ON `crossover-auction-prod`.`auctionLog` (`item_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
